### PR TITLE
Added notes

### PR DESCRIPTION
**Pull request by hjdivad**

### CODE REVIEW

**Comment by hjdivad** [comment]
cc 
@rwjblue @stefanpenner  @trabus  @kategengler @turbo87 @kellyselden

**Comment by kellyselden** [comment]
Wrong fork?

**Comment by hjdivad** [comment]
@kellyselden adding to your pr https://github.com/emberjs/core-notes/pull/168

if you want i can push directly to your pr if you give me commitbit

**Comment by kellyselden** [comment]
@hjdivad Oh my mistake. I understand now.

**Pull request merged**
